"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import ez_setup
ez_setup.use_setuptools()

from setuptools import setup

APP = ['src/face_filter.py']
DATA_FILES = ['src/face_filter_main_window.xib']
OPTIONS = {'argv_emulation': False}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
